name: Continuous Integration

on:
  - push

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup-Go
        uses: actions/setup-go@v3
        with:
          go-version-file: "go.mod"
          cache: true

      - name: Lint-Go
        uses: golangci/golangci-lint-action@v3

  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup-Go
        uses: actions/setup-go@v3
        with:
          go-version-file: "go.mod"
          cache: true

      - name: Unit Test
        run: make test

  generate:
    name: Generate & Diff
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

#      - name: Setup-Go
#        uses: actions/setup-go@v3
#        with:
#          go-version-file: "go.mod"
#          cache: true

      - name: Add asdf-vm install
        uses: asdf-vm/actions/install@v1


      - name: Clean
        run: make clean

      - name: Generate
        run: make generate

      - name: Diff
        run: make diff
